# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0003_auto_20160721_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='id',
        ),
        migrations.AlterField(
            model_name='rating',
            name='object_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
